### ISSUE TITLE
Can't use hypercorn because script says "main.py should be run directly!"

### ISSUE THREAD

**Issue by ghost** [Yo-ru/gulag-web#84]
`* Please use an ASGI server (e.g. Hypercorn) directly in production`
ok...
```
root@gulag:~/gulag-web# hypercorn main.py
Traceback (most recent call last):
  File "/usr/local/bin/hypercorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/hypercorn/__main__.py", line 267, in main
    run(config)
  File "/usr/local/lib/python3.9/dist-packages/hypercorn/run.py", line 34, in run
    worker_func(config)
  File "/usr/local/lib/python3.9/dist-packages/hypercorn/asyncio/run.py", line 178, in asyncio_worker
    app = load_application(config.application_path)
  File "/usr/local/lib/python3.9/dist-packages/hypercorn/utils.py", line 110, in load_application
    module = import_module(import_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/gulag-web/main.py", line 21, in <module>
    raise RuntimeError('main.py should be run directly!')
RuntimeError: main.py should be run directly!
```
what

--------------------
yes I'm running it as root because it's in an LXC container. Ubuntu 18.04.5. Python 3.9.5. Commit b7fff4c70a6beb118f6fe182d29c27429db77886

**Comment by ghost** [comment]
wut how did i assign ppl

**Comment by ghost** [comment]
bruh https://github.com/Yo-ru/gulag-web/blob/b7fff4c70a6beb118f6fe182d29c27429db77886/main.py#L20-L21
